### ISSUE TITLE
Merge same domain stat

### ISSUE THREAD

**Issue by mehmetkose** [vrepsys/blockstats-page#5]
Better theblockstats.com listing stat for same domain

![Screen Shot 2019-03-20 at 15 58 57](https://user-images.githubusercontent.com/706678/54685920-13d55080-4b29-11e9-9aa3-2168207442fc.png)

**Comment by vrepsys** [comment]
Not sure this should be done. Technically they're two different apps.

**Comment by mehmetkose** [comment]
I see. It doesn't make sense but it is what it is.
